# Basic

In [6]:
%reset

Once deleted, variables cannot be recovered. Proceed (y/[n])? y


In [16]:
import torch

print(torch.__version__)
print(torch.backends.mps.is_built()) # Check whether mps is built or not
print(torch.backends.mps.is_available()) # Check availability of mps


1.13.1
True
True


In [ ]:
"""
mps_device = torch.device("mps")

# MPS 장치에 바로 tensor를 생성합니다.
x = torch.ones(5, device=mps_device)
# 또는
x = torch.ones(5, device="mps")

# GPU 상에서 연산을 진행합니다.
y = x * 2

# 또는, 다른 장치와 마찬가지로 MPS로 이동할 수도 있습니다.
model = YourFavoriteNet()  # 어떤 모델의 객체를 생성한 뒤,
model.to(mps_device)       # MPS 장치로 이동합니다.

# 이제 모델과 텐서를 호출하면 GPU에서 연산이 이뤄집니다.
pred = model(x)
"""

In [8]:
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets
from torchvision.transforms import ToTensor, Lambda, Compose
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline
%config InlineBackend.figure_format='retina'

In [10]:
# Load Training Dataset from Open Source
training_data = datasets.MNIST(
    root="data",
    train=True,
    download=True,
    transform=ToTensor()
)

# Load Test Dataset from Open Source
test_data = datasets.MNIST(
    root='data',
    train=False,
    download=True,
    transform=ToTensor()
)

  0%|          | 0/9912422 [00:00<?, ?it/s]

Extracting data/MNIST/raw/train-images-idx3-ubyte.gz to data/MNIST/raw



  0%|          | 0/28881 [00:00<?, ?it/s]

Extracting data/MNIST/raw/train-labels-idx1-ubyte.gz to data/MNIST/raw



  0%|          | 0/1648877 [00:00<?, ?it/s]

Extracting data/MNIST/raw/t10k-images-idx3-ubyte.gz to data/MNIST/raw



  0%|          | 0/4542 [00:00<?, ?it/s]

Extracting data/MNIST/raw/t10k-labels-idx1-ubyte.gz to data/MNIST/raw



In [11]:
batch_size=64

# Create DataLoader
# tf.data.Dataset
train_dataloader = DataLoader(training_data, batch_size=batch_size)
test_dataloader = DataLoader(test_data, batch_size=batch_size)

for X, y in test_dataloader:
    print("Shape of x [N, C, H, W]: ", X.shape)
    print("Shape of y: ", y.shape, y.dtype)
    break

Shape of x [N, C, H, W]:  torch.Size([64, 1, 28, 28])
Shape of y:  torch.Size([64]) torch.int64


In [18]:
device = torch.device("mps")

class NeuralNetwork(nn.Module):
    def __init__(self):
        super(NeuralNetwork, self).__init__()
        self.flatten = nn.Flatten()
        self.linear_relu_stack = nn.Sequential(
                nn.Linear(28*28, 128),
            nn.ReLU(),
            nn.Dropout(.2),
            nn.Linear(128,10)
        )
    def forward(self, x):
        x = self.flatten(x)
        logits = self.linear_relu_stack(x)
        return logits

model = NeuralNetwork().to(device)
print(model)

NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=128, bias=True)
    (1): ReLU()
    (2): Dropout(p=0.2, inplace=False)
    (3): Linear(in_features=128, out_features=10, bias=True)
  )
)


In [22]:
# Setting Loss function and Optimizer
loss_fn = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)

In [21]:
# Training Function
def train(dataloader, model, loss_fn, optimizer):
    size = len(dataloader.dataset)
    for batch, (X, y) in enumerate(dataloader):
        X, y = X.to(device), y.to(device)
        
        # Compute Predicted error
        pred = model(X)
        loss = loss_fn(pred, y)
        
        # BackPropagation
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        
        if batch % 100 == 0:
            loss, current = loss.item(), batch * len(X)
            print(f"loss: {loss:>7f} [{current:>5d}/{size:>5d}]")

In [30]:
# Test Function
def test(dataloader, model, loss_fn):
    size = len(dataloader.dataset)
    num_batches = len(dataloader)
    model.eval()
    test_loss, correct = 0, 0
    # Setting no gradient
    with torch.no_grad():
        for X, y in dataloader:
            X, y = X.to(device), y.to(device)
            pred = model(X)
            test_loss += loss_fn(pred, y).item()
            correct += (pred.argmax(1) == y).type(torch.float).sum().item()
    test_loss /= num_batches
    correct /= size
    print(f"Test Error: \n Accuracy: {(100*correct):>.1f}%, Avg loss: {test_loss:>8f} \n")

In [31]:
epochs = 10
for t in range(epochs):
    print(f"Epoch {t+1}\n{'-'*30}")
    train(train_dataloader, model, loss_fn, optimizer)
    test(test_dataloader, model, loss_fn)
print("Done!")

Epoch 1
------------------------------
loss: 0.063536 [    0/60000]
loss: 0.097155 [ 6400/60000]
loss: 0.067168 [12800/60000]
loss: 0.056007 [19200/60000]
loss: 0.083446 [25600/60000]
loss: 0.113837 [32000/60000]
loss: 0.032853 [38400/60000]
loss: 0.119776 [44800/60000]
loss: 0.102493 [51200/60000]
loss: 0.122135 [57600/60000]
Test Error: 
 Accuracy: 96.8%, Avg loss: 0.102825 

Epoch 2
------------------------------
loss: 0.044799 [    0/60000]
loss: 0.074989 [ 6400/60000]
loss: 0.057560 [12800/60000]
loss: 0.043096 [19200/60000]
loss: 0.063139 [25600/60000]
loss: 0.082683 [32000/60000]
loss: 0.022273 [38400/60000]
loss: 0.086121 [44800/60000]
loss: 0.088209 [51200/60000]
loss: 0.080135 [57600/60000]
Test Error: 
 Accuracy: 97.2%, Avg loss: 0.091518 

Epoch 3
------------------------------
loss: 0.031103 [    0/60000]
loss: 0.065467 [ 6400/60000]
loss: 0.047104 [12800/60000]
loss: 0.037377 [19200/60000]
loss: 0.045875 [25600/60000]
loss: 0.059825 [32000/60000]
loss: 0.018427 [38400/600

# Tensor

In [32]:
# list -> tensor
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


In [34]:
# numpy array -> tensor

#torch.tensor: copy
np_array = np.array(data)
x_np_1 = torch.tensor(np_array)
print(x_np_1)

#torch.as_tensor: view
x_np_2 = torch.as_tensor(np_array)
print(x_np_2)

#torch.from_numpy: view
x_np_3 = torch.from_numpy(np_array)
print(x_np_3)

tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]])


In [35]:
x_np_1[0,0] = 5
print(x_np_1)
print(np_array)

tensor([[5, 2],
        [3, 4]])
[[1 2]
 [3 4]]


In [38]:
x_np_2[0,0] = 6
print(x_np_2)
print(np_array)
print("-"*25)
x_np_3[0,0] = 7
print(x_np_3)
print(np_array)


tensor([[6, 2],
        [3, 4]])
[[6 2]
 [3 4]]
-------------------------
tensor([[7, 2],
        [3, 4]])
[[7 2]
 [3 4]]
